### ISSUE TITLE
Resource links need to be relative to /framework/

### ISSUE THREAD

**Issue by mattjuffs** [mattjuffs/framework#3]
As the framework.html lives in a sub-folder now, since moving to Azure, the resource links are incorrect.

For example:

    /css/*.css

Should be:

    /framework/css/*.css

Either include the `/framework/` sub-folder in the paths, or make them all relative.

**Comment by AaronLayton** [comment]
👍

**Comment by mattjuffs** [comment]
Demo has been updated:
http://slickhouse.com/framework/framework.html

Fixed in commit to /slickhouse:
https://github.com/mattjuffs/slickhouse/commit/c3be6732ad08713637520328a2a486955801a593#diff-756457dc85f13450b3dfba2cbc1465e5
